### ISSUE TITLE
Question: Contribution guidelines?

### ISSUE THREAD

**Issue by NicholasDM** [gaborvecsei/pyTRON#1]
Hi. You might have noticed that I recently made a fork based off of your post on reddit. I really like this and  want to contribute/mess around with my own version, since it seems like a good thing for newer people to play around with.

What are the guidelines for contributing, or for pull requests to the main repository? Would you prefer it stay pretty much as is, or would you like pull requests considered for it? One example is that I switched out msvcrt for getch, with getch being crossplatform (I'm 99% certain). I also bumped it up from Python 2 based to Python 3 based (and all the fun print() stuff that comes with that.)

And with those contribution guidelines, how would you like further modifications/contributors to sign off, as the GPL-3.0 license requests? Specifically,

>  For the developers' and authors' protection, the GPL clearly explains
> that there is no warranty for this free software.  For both users' and
> authors' sake, the GPL requires that modified versions be marked as
> changed, so that their problems will not be attributed erroneously to
> authors of previous versions.

I went ahead and just made a short note at each point where you signed off saying that I modified the version provided. Wanted to make sure that you, as the author, found that appropriate.

Thank you for your time!

**Comment by gaborvecsei** [comment]
Hi.
First of all, thank you for the interest!

I would like to stay with my version, because I would like to update it, when I will have time, but of course, you can play with it and you can do whatever you want with this repo as long as you mention me as the original author.

If you will have a cross platform version and you'll making bigger changes than I would like to see it and I am open to pull requests.

So I think that's it. If you have any further questions I'll be here.
